# Generated by Django 3.1 on 2020-08-30 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('height', models.CharField(default='', max_length=255)),
                ('mass', models.CharField(default='', max_length=255)),
                ('hair_color', models.CharField(default='', max_length=255)),
                ('skin_color', models.CharField(default='', max_length=255)),
                ('eye_color', models.CharField(default='', max_length=255)),
                ('birth_year', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('species_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('population', models.CharField(default='0', max_length=255)),
                ('known_residents_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('personaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='starwars.people')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars.planet'),
        ),
    ]
